image:
  file: .gitpod.dockerfile
  context: nginx
ports:
- port: 8002
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo "Start nginx with php-fpm7.4 and multitail";
    echo -e "\t nginx & /usr/sbin/php-fpm7.4 --fpm-config php-fpm.conf && multitail /var/log/nginx/access.log -I /var/log/nginx/error.log";
    echo "Stop nginx and php-fpm7.4 and multitail";
    echo -e "\t nginx -s stop && pkill php-fpm && pkill multitail"
    echo "Reload nginx"
    echo -e "\t nginx -s reload"